version: '3'

services:
  docker-mysql:
    image: gs-securing-web-0.1.0.jar:latest
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=youtube
      - MYSQL_PASSWORD=
  spring-boot-jpa-docker-webapp:
    image: gradle-springboot
    depends_on:
      - docker-mysql
    ports:
      - 8085:8085
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=test
      - DATABASE_PORT=3306